### ISSUE TITLE
Error on transitions

### ISSUE THREAD

**Issue by kakwok** [HCALRunControl/levelOneHCALFM#80] opened 2016-05-15 10:44 UTC
It appears as ERROR on stop, first error like this:
 2016-05-15 11:30:13 and 473 ms : cms.hcalpro.rcms.fm.app.level1.HCALEventHandler
      INFO [SethLog HCAL HCAL_HBHEc] 2 received id: http://hcalvme03.cms:17200/urn:xdaq-application:lid=50, ToState: failed
 2016-05-15 11:30:13 and 473 ms : cms.hcalpro.rcms.fm.app.level1.HCALEventHandler
     ERROR [HCAL HCAL_HBHEc] Error! computeNewState() for FM@ URI: http://cmsrc-hcal.cms:16000/urn:rcms-fm:fullpath=/hcalpro/USC/Local_multipartition/HCAL_all_multipartition_v93,group=HCAL_HBHEc,owner=hcalpro
the Resource: http://hcalvme03.cms:17200/urn:xdaq-application:lid=50 reports an error state!

But I noticed a bunch of warnings before that:

 2016-05-15 11:30:15 and 437 ms : cms.hcalpro.rcms.util.logsession.OracleLogSessionConnector
      WARN Log Session with id 279496 is already closed
 2016-05-15 11:30:15 and 437 ms : cms.hcalpro.rcms.fm.app.level1.HCALFunctionManager
      WARN [HCAL HCAL_HO] Could not close sessionId, but sessionId was requested and used.This is OK only for global runs.
Exception:

 2016-05-15 11:30:15 and 793 ms : cms.hcalpro.rcms.fm.resource.qualifiedresource.FunctionManager
      WARN FunctionManager getParameter problem URI=http://cmsrc-hcal.cms:16000/urn:rcms-fm:fullpath=/hcalpro/USC/Local_multipartition/HCAL_all_multipartition_v93,group=HCAL_HO,owner=hcalpro
 2016-05-15 11:30:15 and 793 ms : cms.hcalpro.rcms.fm.app.level1.HCALEventHandler
      WARN [HCAL HCAL_LEVEL_1] Could not update parameters for FM client: HCAL_HO The exception is:

**Comment by jhakala** [comment] 2016-05-25 10:13
Is this reproducible? Have we observed it again?

**Comment by jhakala** [comment] 2016-05-30 17:18
I haven't been able to spot this in the logs anywhere so I think this was a fluke. Perhaps related to a temporary database hiccup.

**Comment by jhakala** [comment] 2016-06-05 20:23
I've observed stopping issues at least two times in the last two weeks.

Looking at the logs for one of the instances, I see the hcalSupervisor reports failed but no other useful logs were present. This looks to be a xdaq bug, perhaps associated with the new notifications scheme, so I'll put this under a new label designated for xdaq/HCALFM interfacing issues.

**Comment by sethcooper** [comment] 2016-06-23 16:24
This may be TCDS related.
More debugging information needed to proceed further.
Implementation of issue #33 would probably help with this.

**Comment by jhakala** [comment] 2016-06-25 13:19
Also seems to be happening on starting now. Upping this to showstopper.

**Comment by kakwok** [comment] 2016-06-26 08:48
TCDS people investigating

**Comment by jhakala** [comment] 2016-06-27 06:55
Let's try to organize this. Please correct me if I'm wrong about this but I think we have three entangled issues here:
1) HCAL TCDS apps crash occasionally
2) Communication with HCAL TCDS apps hangs on their side due to sockets being busy
3) The supervisor sometimes takes a strange amount of time to go through the enable transition

All three lead to timeouts. Correct?

**Comment by kakwok** [comment] 2016-06-27 08:06
We only see 1) and 3) over the weekend. 1) happened on stopping, but the crash would prevent us from subsequent init if the crashed app is not restarted.
3) happened on starting.
Haven't seen 2) for awhile.

**Comment by jhakala** [comment] 2016-07-12 19:13
Fixed by Jeremy/Andrea

**Closed by jhakala** 2016-07-12 19:13 UTC
Labels: (high), (show stopper), xdaq related
